spring.application.name=patient-api

spring.datasource.url=jdbc:postgresql://localhost:5432/patient_lookup
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
jwt.secret=${JWT_SECRET}
jwt.expiration=518400000

logging.level.org.springframework.security=DEBUG